package.yaml
=> Make everything strict

package.yaml
=> Include replays in extra source files

library/Rattletrap/Header.hs, library/Rattletrap/Primitive/Dictionary.hs
=> Store dictionaries as maps

.hindent.yaml, library/Rattletrap.hs, library/Rattletrap/Attribute.hs, library/Rattletrap/ClassAttributeMap.hs, library/Rattletrap/Content.hs, library/Rattletrap/Crc.hs, library/Rattletrap/Frame.hs, library/Rattletrap/Header.hs, library/Rattletrap/Initialization.hs, library/Rattletrap/KeyFrame.hs, library/Rattletrap/Main.hs, library/Rattletrap/Mark.hs, library/Rattletrap/Message.hs, library/Rattletrap/Primitive/Dictionary.hs, library/Rattletrap/Primitive/Section.hs, library/Rattletrap/Property.hs, library/Rattletrap/PropertyValue.hs, library/Rattletrap/Replay.hs, library/Rattletrap/Replication/Destroyed.hs, library/Rattletrap/Replication/Spawned.hs, library/Rattletrap/ReplicationValue.hs
=> Add documentation

library/Rattletrap/Primitive/Text.hs, library/Rattletrap/RemoteId.hs, library/Rattletrap/Utility.hs
=> Improve parsing of remote IDs

source/library/Rattletrap.hs, source/library/Rattletrap/Helper.hs
=> Add helpers for encoding and decoding replays and JSON

tools/attach-binary.hs
=> Fix attach binary script

.codeclimate.yml, .travis.yml, README.markdown
All this really buys me is a service that runs HLint against my code.
=> Set up Code Climate

source/library/Rattletrap/Helper.hs
They basically don't work, thanks to lazy IO. Also I never use them.
=> Remove file and handle helpers

library/Rattletrap/Main.hs, package.yaml
=> Accept URLs as input arguments

package.yaml
=> Remove support for older GHC versions

.github/workflows/ci.yaml
=> Add ".exe" extension to Windows artifacts

.github/workflows/ci.yaml, rattletrap.cabal, stack.yaml
Also drop support for 8.6 and 8.8.
=> Upgrade to GHC 8.10.3

rattletrap.cabal, src/lib/Rattletrap/Type/Int64le.hs, src/lib/Rattletrap/Type/Word64le.hs, src/test/Main.hs
=> Stop accepting JSON numbers for 64-bit values

src/lib/Rattletrap/Console/Main.hs
=> Exit successfully when showing help or version

.github/workflows/ci.yaml
https://github.com/tfausak/rattletrap/pull/214#issuecomment-790229979
=> Fix release CI again

.github/workflows/ci.yaml
https://github.com/tfausak/rattletrap/pull/215#issuecomment-790252621
=> Fix release CI yet again

.github/workflows/ci.yaml, src/test/Main.hs, src/util/copy-executable.hs
=> Really fix release CI

.github/workflows/ci.yaml, src/test/Main.hs
=> Try to fix release CI

.github/workflows/ci.yaml, cabal.project
#219 
https://github.com/tfausak/rattletrap/runs/2039837690?check_suite_focus=true#step:9:4
=> Fix Docker build

rattletrap.cabal, src/lib/Rattletrap/Type/Attribute/PartyLeader.hs, src/lib/Rattletrap/Type/RemoteId.hs, src/lib/Rattletrap/Type/RemoteId/Epic.hs, src/lib/Rattletrap/Type/RemoteId/PlayStation.hs, src/lib/Rattletrap/Type/RemoteId/PsyNet.hs, src/lib/Rattletrap/Type/RemoteId/Splitscreen.hs, src/lib/Rattletrap/Type/RemoteId/Steam.hs, src/lib/Rattletrap/Type/RemoteId/Switch.hs, src/lib/Rattletrap/Type/RemoteId/Xbox.hs
=> Split out remote ID types

.github/workflows/ci.yaml, src/lib/Rattletrap/Console/Main.hs, src/util/check-schema.hs
=> Test JSON against schema

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/ci.yaml
=> Compress executables with UPX

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/ci.yaml, README.markdown, rattletrap.cabal, stack.yaml
=> Upgrade to GHC 9.0.1

src/lib/Rattletrap/Type/CompressedWord.hs, src/lib/Rattletrap/Type/Replay.hs, src/test/Main.hs
=> Handle replays with large actor IDs

.github/workflows/ci.yaml, rattletrap.cabal
Fixes #260. 
Not sure if this will build or not.
=> Downgrade to GHC 9.2.1 on Windows

.devcontainer/Dockerfile, .github/workflows/ci.yaml, .gitignore, rattletrap.cabal
=> Fix Windows executable

rattletrap.cabal, src/lib/Rattletrap/Schema.hs, src/lib/Rattletrap/Utility/Json.hs
https://github.com/commercialhaskell/stackage/issues/6615
=> Allow aeson 2.1

.github/workflows/workflow.yaml, rattletrap.cabal
https://github.com/tfausak/haskell-packages/pull/3
=> Add support for GHC 9.6.1

.github/workflows/workflow.yaml, src/util/check-schema.hs
https://github.com/tfausak/haskell-packages/pull/8
=> Upgrade Ormolu action

cabal.project, rattletrap.cabal, src/lib/Rattletrap/Utility/Json.hs
https://github.com/commercialhaskell/stackage/issues/7031
=> Allow aeson 2.2

.devcontainer/compose.yaml, .devcontainer/devcontainer.json, .github/workflows/workflow.yaml, rattletrap.cabal, src/lib/Rattletrap/Utility/Json.hs
https://github.com/tfausak/haskell-packages/pull/15
=> Upgrade to GHC 9.8.1

rattletrap.cabal
https://github.com/commercialhaskell/stackage/issues/7216
=> Allow bytestring 0.12

.github/workflows/workflow.yaml
See problem here: https://github.com/tfausak/rattletrap/actions/runs/8773536361/job/24074044254#step:4:7
=> Fix artifact names for releases

.github/workflows/workflow.yaml
Very quiet warning for this: https://github.com/tfausak/rattletrap/actions/runs/8773930762/job/24074778328#step:10:10
=> Fix schema release asset
